name: Test

on:
  push:
    branches: [main, staging, trying]
  pull_request:
    branches: [main]
    
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test
